# (C) 2023 J.F.Dockes

#
# MS-WINDOWS specific definitions for recoll.conf
#

# Replace the default '~' which is confusing for Windows user. path_tildexpand() very narrowly
# processes %USERPROFILE% (just replace it with ~ at the start of a value).
topdirs = %USERPROFILE%

# We used to have no way to identify files without a suffix, or with an unknown one on
# Windows. Circa recoll 1.34.2, a libmagic port was used and it became possible. Still the change
# has a great surprise potential, too much for a minor release. For now default to not using
# identification from data.
usesystemfilecommand = 0

# /media which is the default on Linux makes no sense on Windows
skippedPaths =
